### ISSUE TITLE
"item.evaluate is not a function" when using create as in docs

### ISSUE THREAD

**Issue by abp** [SteveSanderson/knockout.mapping#3] opened 2010-12-21 18:35 UTC
Hi,

i have a mapping for fromJs with create like in the docs section "Customizing object construction using “create”" in http://knockoutjs.com/documentation/plugins.mapping.html
So i'm extending the data with dependentObservables and subscriptions.

The line 126 in knockout.mapping.debug.js gives me an error as stated in the title.
The error is reproducable with the sample from the metioned docs section.

For now i can work and test with the line commented. Will this have any side effects?

**Comment by sagacity** [comment] 2010-12-21 19:18
This is caused by the fact that the way the creation of dependentObservable is deferred has changed slightly since I first wrote the plugin. In fact, the line _needs_ to be commented out, so your workaround is perfectly fine.

I'll try to make a proper fix asap and close this issue once it is committed. Thanks for reporting!

**Comment by sagacity** [comment] 2010-12-22 14:39
This is now fixed.

**Closed as completed** 2010-12-22 22:39 UTC

**Comment by abp** [comment] 2010-12-23 08:40
Wow, thanks for the effort. :)
